### ISSUE TITLE
can not initialize Inspector Window Utility

### ISSUE THREAD

**Issue by noonoox** [slavniyteo/one-line#47] opened 2020-09-23 21:38 UTC
**General Info**
OS: Windows 10
Unity Version: 2020.1.5 (and .1.6)
OneLine Version: Latest on Unity Store
OneLine Installation: Unity Package Manager

---

**Describe the bug**
When selecting Assets/Example/Overview/Overview.asset, this message fills the console.

OneLine can not initialize Inspector Window Utility. 
You may experience some performance issues. 
Please create an issue on https://github.com/slavniyteo/one-line/ and we will repair it.

System.NullReferenceException: Object reference not set to an instance of an object
  at OneLine.InspectorUtil.Initialize () [0x00010] in C:\Users\noono\Documents\Unity Projects\Sulgeda\Assets\Plugins\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:51 
  at OneLine.InspectorUtil..ctor () [0x00039] in C:\Users\noono\Documents\Unity Projects\Sulgeda\Assets\Plugins\OneLine\OneLine\Editor\Utils\InspectorUtil.cs:41 
UnityEngine.Debug:LogError(Object)
OneLine.InspectorUtil:.ctor() (at Assets/Plugins/OneLine/OneLine/Editor/Utils/InspectorUtil.cs:45)
OneLine.OneLinePropertyDrawer:.ctor() (at Assets/Plugins/OneLine/OneLine/Editor/OneLinePropertyDrawer.cs:36)
UnityEditor.Editor:DrawDefaultInspector()
EasyButtons.ObjectEditor:OnInspectorGUI() (at Assets/Plugins/EasyButtons/Assets/EasyButtons/Editor/ButtonEditor.cs:17)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by slavniyteo** [comment] 2020-09-24 09:13
Seem to be duplicate of #34 

**To disable the error message:** go to Window/OneLineSettings and switch off the Culling column (the second from the right).

**Closed by slavniyteo** 2020-09-24 09:13 UTC
Labels: bug
