### ISSUE TITLE
One line does not work?

### ISSUE THREAD

**Issue by kk3hi3123** [slavniyteo/one-line#33] opened 2019-01-18 09:10 UTC
The OneLine examples work as instruction. But when I copy one of the example code to another .cs file and change its name, the new class does not work. Do I miss something like setting or initialize?

**Comment by slavniyteo** [comment] 2019-01-18 09:15
Show me what do you do exactly.

**Comment by kk3hi3123** [comment] 2019-01-22 02:01
1. I start a new project.
2. Import OneLine.
3. Add a new C# Script.
4. Copy from OneLineExample.cs and copy it to my new C# Script.
5. Remove namespace OneLine.Example, change the class name and menuName.

And here is the result after I create a new asset.
<img width="366" alt="screenshot 2019-01-22 at 9 13 47 am" src="https://user-images.githubusercontent.com/20828545/51507466-0c950d80-1e2c-11e9-824b-a14ae4aecf8a.png">

I am using Unity 2018.2.14f1 and here is the project.
[TestingProject.zip](https://github.com/slavniyteo/one-line/files/2781008/TestingProject.zip)

**Comment by slavniyteo** [comment] 2019-01-23 01:36
Ok, there it is.

Look at the screenshot, at the first property `Script`  lies `None (Mono Script)`, but must be the name of class. This mean that Unity can't properly load your script.
![image](https://user-images.githubusercontent.com/18638390/51576342-deb0d700-1ec6-11e9-9969-f8debafbab6e.png)

I've looked through your project. The problem is that you named the file `Data.cs`, but class inside it is `DataAsset`. In Unity file must have the same name as public class incide it (this is suitable for classes which inherit from `UnityEngine.Object`, for example `MonoBehaviour`'s and `ScriptableObject`'s).

So rename file to `DataAsset.cs` and this is the solution.

I close the issue, but If your problem is not solved completely, feel free to reopen it.

---

P.S. When you send your project to someone, or if you use version control system (like Git or SVN), all you need to store is:

- Asset directory;
- ProjectSettings directory;
- Packages directory;

The rest is temporary files that will be regenerated on the other PC.

**Closed by slavniyteo** 2019-01-23 01:36 UTC
