### ISSUE TITLE
OneLine cannot initialize Inspector Window Utility

### ISSUE THREAD

**Issue by CustomPhase** [slavniyteo/one-line#48] opened 2020-09-29 10:35 UTC
**General Info**
OS: Windows 10
Unity Version: 2020.2.0b2
OneLine Version: 0.5.1
OneLine Installation: Package Manager
RectEx Version: didnt change

---

Trying to use it on a list of custom struct. Im using Odin Serializer, maybe thats somehow affects it.

![image](https://user-images.githubusercontent.com/10864826/94547907-5c66e180-0269-11eb-80ca-135fc700ef69.png)

OneLine can not initialize Inspector Window Utility. 
You may experience some performance issues. 
Please create an issue on https://github.com/slavniyteo/one-line/ and we will repair it.

System.NullReferenceException: Object reference not set to an instance of an object
  at OneLine.InspectorUtil.Initialize () [0x00010] in D:\Games\Unity\MyProjects\SkatePrototypeV2\Library\PackageCache\st.one-line@321188262e\Editor\Scripts\Utils\InspectorUtil.cs:51 
  at OneLine.InspectorUtil..ctor () [0x00039] in D:\Games\Unity\MyProjects\SkatePrototypeV2\Library\PackageCache\st.one-line@321188262e\Editor\Scripts\Utils\InspectorUtil.cs:41 
UnityEngine.Debug:LogError (object)
OneLine.InspectorUtil:.ctor () (at Library/PackageCache/st.one-line@321188262e/Editor/Scripts/Utils/InspectorUtil.cs:45)
OneLine.OneLinePropertyDrawer:.ctor () (at Library/PackageCache/st.one-line@321188262e/Editor/Scripts/OneLinePropertyDrawer.cs:36)
UnityEditor.ScriptAttributeUtility:GetHandler (UnityEditor.SerializedProperty)
UnityEditorInternal.ReorderableList:CacheIfNeeded (bool)
UnityEditorInternal.ReorderableList:GetListElementHeight ()
UnityEditorInternal.ReorderableList:DoList (UnityEngine.Rect,UnityEngine.Rect)
UnityEditorInternal.ReorderableListWrapper:Draw (UnityEngine.Rect,UnityEngine.Rect)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by slavniyteo** [comment] 2020-09-29 11:36
Seem to be duplicate of #34 and #47 

To disable the error message: go to Window/OneLineSettings and switch off the Culling column (the second from the right).

**Closed by slavniyteo** 2020-09-29 11:36 UTC
Labels: bug
